import java.lang.Object;
import java.lang.String;
import java.io.*;
public class FinallyJava2{
    public static void main(String[] args) throws IOException{
        BufferedReader in = new BufferedReader(new FileReader("file.txt"));
        try{
            String line;
            while((line = in.readLine())!= null){
                System.out.println(line);
                in = new BufferedReader(new FileReader("something.txt"));
            }
        }
        finally{
            if(in!= null){
                try{
                    in.close();
                }
                catch(Exception e){
                    System.out.println("in cannot be closed due to some error");
                }
            }
            try{
                if(in!= null){
                    in.close();
                }
            }
            catch(Exception e){
                System.out.println("in has still not been closed :(");
            }
            in = null;
        }
    }
}
 
import java.lang.Object;
import java.lang.String;
import java.io.*;
public class FinallyJava3{
    public static void main(String[] args) throws IOException, ArithmeticException{
    long num = 1L;
        long result = 0;  
        try{
            for(int i = 1; i < 10000000; i++){
                result += num + 1;
            }
        }
        catch(ArithmeticException e){
            System.out.println("Number is too big and will throw an ArithmeticException!");
        }
        catch(IOException ie){
            System.out.println("Number is too big and will throw an FileNotFoundException!");
        }
        catch(Exception e){
            System.out.println("Unknown exception!");
        }
        finally{
            System.out.println("Result is: " + result);
        }
    }
}
